# Generated by Django 5.0.7 on 2024-08-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oohoo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='update',
            new_name='Person',
        ),
    ]
