# Generated by Django 5.0.7 on 2024-08-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oohoo', '0002_rename_update_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='MyModel',
        ),
    ]
